### ISSUE TITLE
Lab5 - vowel counting loop

### ISSUE THREAD

**Issue by DaiSwap** [DiviyamPathak/Microprocessorlabasmx86#1]
The code does not correctly count vowels because it skips some operations and has unreachable code.
    Improvement: Ensure the 'vowels' label increments 'vvowelcount' and the control flow is correctly managed.

Assembly - 

movl $0, %ecx
loop:
movb string(, %ecx, 1), %al
cmpb $97, %al
je vowels
cmpb $101, %al
je vowels
cmpb $105, %al
je vowels
cmpb $111, %al
je vowels
cmpb $117, %al
je vowels
jmp loopforcheck
vowels:
addl $1, vvowelcount
loopforcheck:
addl $1, %ecx
cmpl $18, %ecx
jne loop
jmp removecharatfirst

**Comment by DiviyamPathak** [comment]
good but this ia an issue not pr raise a pr request

**Comment by DaiSwap** [comment]
oh okay , raising issue -
